export const TIP_REQUIREMENTS_GET = 'TIP_REQUIREMENTS_GET';

export const TIP_SERVERS_CREATE = 'TIP_SERVERS_CREATE';
export const TIP_SERVERS_READ = 'TIP_SERVERS_READ';
export const TIP_SERVERS_UPDATE = 'TIP_SERVERS_UPDATE';
export const TIP_SERVERS_DELETE = 'TIP_SERVERS_DELETE';
