export const EVT_MODULES_CREATE = 'EVT_MODULES_CREATE';
export const EVT_MODULES_READ = 'EVT_MODULES_READ';
export const EVT_MODULES_UPDATE = 'EVT_MODULES_UPDATE';
export const EVT_MODULES_DELETE = 'EVT_MODULES_DELETE';

export const EVT_REQUIREMENTS_GET = 'EVT_REQUIREMENTS_GET';

export const EVT_SECRETS_CREATE = 'EVT_SECRETS_CREATE';
export const EVT_SECRETS_READ = 'EVT_SECRETS_READ';
export const EVT_SECRETS_UPDATE = 'EVT_SECRETS_UPDATE';
export const EVT_SECRETS_DELETE = 'EVT_SECRETS_DELETE';

export const EVT_SERVERS_CREATE = 'EVT_SERVERS_CREATE';
export const EVT_SERVERS_READ = 'EVT_SERVERS_READ';
export const EVT_SERVERS_UPDATE = 'EVT_SERVERS_UPDATE';
export const EVT_SERVERS_DELETE = 'EVT_SERVERS_DELETE';

export const EVT_TENANTS_CREATE = 'EVT_TENANTS_CREATE';
export const EVT_TENANTS_READ = 'EVT_TENANTS_READ';
export const EVT_TENANTS_UPDATE = 'EVT_TENANTS_UPDATE';
export const EVT_TENANTS_DELETE = 'EVT_TENANTS_DELETE';

export const EVT_WORKSPACES_CREATE = 'EVT_WORKSPACES_CREATE';
export const EVT_WORKSPACES_READ = 'EVT_WORKSPACES_READ';
export const EVT_WORKSPACES_UPDATE = 'EVT_WORKSPACES_UPDATE';
export const EVT_WORKSPACES_DELETE = 'EVT_WORKSPACES_DELETE';
