export const TIP_MODULES_CREATE = 'TIP_MODULES_CREATE';
export const TIP_MODULES_READ = 'TIP_MODULES_READ';
export const TIP_MODULES_UPDATE = 'TIP_MODULES_UPDATE';
export const TIP_MODULES_DELETE = 'TIP_MODULES_DELETE';

export const TIP_REQUIREMENTS_GET = 'TIP_REQUIREMENTS_GET';

export const TIP_SECRETS_CREATE = 'TIP_SECRETS_CREATE';
export const TIP_SECRETS_READ = 'TIP_SECRETS_READ';
export const TIP_SECRETS_UPDATE = 'TIP_SECRETS_UPDATE';
export const TIP_SECRETS_DELETE = 'TIP_SECRETS_DELETE';

export const TIP_SERVERS_CREATE = 'TIP_SERVERS_CREATE';
export const TIP_SERVERS_READ = 'TIP_SERVERS_READ';
export const TIP_SERVERS_UPDATE = 'TIP_SERVERS_UPDATE';
export const TIP_SERVERS_DELETE = 'TIP_SERVERS_DELETE';

export const TIP_TENANTS_CREATE = 'TIP_TENANTS_CREATE';
export const TIP_TENANTS_READ = 'TIP_TENANTS_READ';
export const TIP_TENANTS_UPDATE = 'TIP_TENANTS_UPDATE';
export const TIP_TENANTS_DELETE = 'TIP_TENANTS_DELETE';

export const TIP_WORKSPACES_CREATE = 'TIP_WORKSPACES_CREATE';
export const TIP_WORKSPACES_READ = 'TIP_WORKSPACES_READ';
export const TIP_WORKSPACES_UPDATE = 'TIP_WORKSPACES_UPDATE';
export const TIP_WORKSPACES_DELETE = 'TIP_WORKSPACES_DELETE';
